version: "3.7"

services:
  app:
    depends_on:
      - mysql
    image: carpricetask
    container_name: carpricetask
    ports:
      - 8080:8080
    working_dir: /app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: BOOK_CATALOG
  mysql:
    image: carpricetask_mysql
    ports:
      - 3306:3306
    container_name: carpricetask_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BOOK_CATALOG