version: "3.7"

services:
  db:
    container_name: carpricetask_mysql
    build: 
      context: .
      dockerfile: db.Dockerfile
    platform: linux/x86_64
    restart: always
    networks:
      - default
    ports:
      - 3306:3306   
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BOOK_CATALOG  
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    container_name: carpricetask_app
    build: 
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - db
    restart: always
    networks:
      - default
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: BOOK_CATALOG  
    
volumes:
  mysql-data:

networks:
   default: